### ISSUE TITLE
Meta: Github organization for web stuff

### ISSUE THREAD

**Issue by IainNZ** [JuliaWeb/HttpServer.jl#29]
About a year ago, the `Http*` stuff was under `hackerschool/`. We moved it to JuliaLang at the time because there was bit rot and all the people who had made it had moved on from Hacker School.

I think that it'd mayyybe a good time now to split it out into its own organization, with this possible list of packages:
- [x] GeoIP http://github.com/johnmyleswhite/GeoIP.jl @johnmyleswhite (abandonware right now)
- [x] GnuTLS http://github.com/Keno/GnuTLS.jl @Keno 
- [x] HTTPClient http://github.com/amitmurthy/HTTPClient.jl @amitmurthy 
- [x] HttpCommon
- [x] HttpParser
- [x] HttpServer
- [x] LibCURL http://github.com/amitmurthy/LibCURL.jl
- [x] Meddle http://github.com/JuliaLang/Meddle.jl
- [x] Morsel http://github.com/JuliaLang/Morsel.jl
- [x] Requests http://github.com/Keno/Requests.jl
- [x] SMTP http://github.com/aviks/SMTPClient.jl @aviks 
- [x] UAParser http://github.com/randyzwitch/UAParser.jl @randyzwitch
- [x] URIParser http://github.com/Keno/URIParser.jl
- [x] URITemplate http://github.com/Keno/URITemplate.jl
- [x] WebSockets http://github.com/JuliaLang/WebSockets.jl
### Deprecate
- [x] Curl http://github.com/forio/Curl.jl @forio
- [x] URLParse http://github.com/tanmaykm/URLParse.jl @tanmaykm 

Thoughts?
(This may just be shuffling papers around on my virtual Github desk for little gain)
